import Head from 'next/head'
import { Inter } from 'next/font/google'
import Link from 'next/link';
import { useContext } from 'react';
import AuthContext from '@/context/AuthContext';
import Button from '@/components/common/Button';
import styles from '../styles/Lobby.module.scss'
import { useRouter } from 'next/router';
import logoutLogo from '../public/logout.svg'
import Image from 'next/image';


const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const { user, logout } = useContext(AuthContext);
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Fira+Sans" />
        <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,wght@0,200;1,200&family=Oswald&family=Signika+Negative:wght@500&display=swap" rel="stylesheet" />
      </Head>
      <div className='text-center flex-center w-full h-full-vh relative'>
        <div className=''>
          <h1 className='fs-40 c-white'>Welcome to Warland !</h1>
          {!!user ? (
            <Button label="Invite a Friend" classes={`${styles.redBtn} flex-center relative h-45 w-full mt-3 fs-18 font-oswald text-white`} onClick={() => router.push('/invite')} />
          ) : (
            <div className='mt-5 fs-20 c-white'>
              <Link href="/signup" className='c-white'>
                Sign Up
              </Link>
              <span className='mx-1'>or</span>
              <Link href="/login" className='c-white'>
                Login
              </Link>
              <span className='mx-1'>to start playing.</span>
            </div>
          )}
        </div>
        <div className='absolute right-20 bottom-10 rounded-full bg-black border-white h-60 w-60 flex-center cursor-pointer' onClick={logout}>
          <Image src={logoutLogo} alt="/logout" />
        </div>
      </div>
    </>
  )
}

